### ISSUE TITLE
Implement automatic color scheme changing between light and dark

### ISSUE THREAD

**Issue by kovidgoyal** [kovidgoyal/kitty-fosshack2024#3]
Allow specifying color themes for light and dark mode and switch automatically between them based on system color theme state.

Will require a new option in kitty.conf, something like

light_and_dark_mode_themes theme name 1, theme name 2

Integration points:

Boss.on_system_color_scheme_change
Boss.patch_colors

Get a named theme as a .conf file by running
kitten themes --dump-theme --check-age=-1 Theme Name

Then parse that into a color dict to call patch_colors with. See rc/set_colors.py for an example of doing that.

When calling the kitten handle the theme not being downloaded by recalling with --cache-age=0

Also use an IPC mutex so that if there are multiple kitty's running they dont all call the kitten at the same time.

Pure python unless some changes to the themes kittne need to be made, which would be in Go.

**Comment by KishanJainSP** [comment]
Hey @kovidgoyal
Our team would like work upon this issue under FOSS Hack 2024 please assign this issue to us

**Comment by kovidgoyal** [comment]
Done.

**Comment by klmcwhirter** [comment]
@KishanJainSP did your team lose interest in carrying this further?

I have just started using Dark color scheme once in a while, and am looking to build some sort of "plugin" to perform the switch to prototype.

But do not want to duplicate effort.

**Comment by KishanJainSP** [comment]
@kovidgoyal I'm really sorry to say this,the teammates I was working on this project with has got parted from team so unfortunately I couldn't carry this project on my own 
Please unassigned this project 
And if I ever could gather team mates for your projects I'll surely be working on Kitty's Projects
Sorry if this ever created any inconveniences

**Comment by kovidgoyal** [comment]
sure, no worries

**Comment by kovidgoyal** [comment]
This is now implemented in kitty master

**Comment by jackbravo** [comment]
Putting this link here just for reference :-p

https://github.com/kovidgoyal/kitty/commit/466bc8933ae333c2c33e8289a8192e06013e68a5
